openapi: 3.0.1
info:
  contact:
    email: gdiazw@alumnos.unex.es
    name: Smart GreenAdapt
    url: http://spilab.es/
  description: Esta API provee los servicios necesarios para gestionar los datos recogidos
    por los dispositivos Arduino y sus sensores.
  termsOfService: http://spilab.es/
  title: Smart GreenAdapt
  version: "1.0"
servers:
- url: /
paths:
  /airquality:
    delete:
      description: Eliminaci贸n de un dato de la calidad del aire guardado en la base
        de datos.
      operationId: deleteAirQuality
      parameters:
      - description: Id de la calidad del aire
        explode: true
        in: query
        name: idAirQuality
        required: true
        schema:
          format: int32
          type: integer
        style: form
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Eliminaci贸n de datos de la calidad del aire.
      tags:
      - Calidad del aire
      x-swagger-router-controller: CalidadDelAire
    get:
      description: Devuelve todos los datos relacionados con la calidad del aire.
      operationId: getAirQuality
      parameters:
        - description: Id del invernadero
          explode: true
          in: query
          name: idGreenhouse
          required: true
          schema:
            format: int32
            type: integer
          style: form
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Devuelve todos los datos relacionados con la calidad del aire.
      tags:
        - Calidad del aire
      x-swagger-router-controller: CalidadDelAire
    post:
      description: Creacion de nuevos datos asociados a la calidad del aire.
      operationId: postAirQuality
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AirQuality'
        required: true
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Registra un nuevo dato de calidad del aire.
      tags:
      - Calidad del aire
      x-swagger-router-controller: CalidadDelAire
    put:
      description: Modifica un dato de calidad del aire previamente registrado
      operationId: putAirQuality
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AirQuality'
        required: true
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Modifica un dato de calidad del aire previamente registrado
      tags:
      - Calidad del aire
      x-swagger-router-controller: CalidadDelAire
  /luminosity:
    delete:
      description: Eliminaci贸n un dato de luminosidad en la base de datos.
      operationId: deleteLuminosity
      parameters:
      - description: Id del dato de luminosidad
        explode: true
        in: query
        name: idLuminosity
        required: true
        schema:
          format: int32
          type: integer
        style: form
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Eliminaci贸n de datos de luminosidad.
      tags:
      - Luminosidad
      x-swagger-router-controller: Luminosidad
    get:
      description: Devuelve todos los datos relacionados con la luminosidad.
      operationId: getLuminosity
      parameters:
        - description: Id del invernadero
          explode: true
          in: query
          name: idGreenhouse
          required: true
          schema:
            format: int32
            type: integer
          style: form
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Devuelve todos los datos relacionados con la luminosidad.
      tags:
      - Luminosidad
      x-swagger-router-controller: Luminosidad
    post:
      description: Creacion de nuevos datos asociados a la luminosidad.
      operationId: postLuminosity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Luminosity'
        required: true
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Registra un nuevo dato de luminosidad.
      tags:
      - Luminosidad
      x-swagger-router-controller: Luminosidad
    put:
      description: Modifica un dato de luminosidad previamente registrado
      operationId: putLuminosity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Luminosity'
        required: true
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Modifica un dato de luminosidad previamente registrado
      tags:
      - Luminosidad
      x-swagger-router-controller: Luminosidad
  /notification:
    get:
      description: Devuelve todos los datos relacionados con notificaciones.
      operationId: getNotification
      parameters:
        - description: Id del invernadero
          explode: true
          in: query
          name: idGreenhouse
          required: true
          schema:
            format: int32
            type: integer
          style: form
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Devuelve todos los datos relacionados con notificaciones.
      tags:
      - Notificacion
      x-swagger-router-controller: Notificacion
    post:
      description: Creacion de nuevas notificaciones.
      operationId: postNotification
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notification'
        required: true
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Registra una nueva notificaci贸n.
      tags:
      - Notificacion
      x-swagger-router-controller: Notificacion
  /humidity:
    delete:
      description: Eliminaci贸n un dato de humedad en la base de datos.
      operationId: deleteHumidity
      parameters:
      - description: Id del dato de humedad
        explode: true
        in: query
        name: idHumidity
        required: true
        schema:
          format: int32
          type: integer
        style: form
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Eliminaci贸n de datos de humedad.
      tags:
      - Humedad
      x-swagger-router-controller: Humedad
    get:
      description: Devuelve todos los datos relacionados con la humedad.
      operationId: getHumidity
      parameters:
        - description: Id del invernadero
          explode: true
          in: query
          name: idGreenhouse
          required: true
          schema:
            format: int32
            type: integer
          style: form
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Devuelve todos los datos relacionados con la humedad.
      tags:
      - Humedad
      x-swagger-router-controller: Humedad
    post:
      description: Creacion de nuevos datos asociados a la humedad.
      operationId: postHumidity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Humidity'
        required: true
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Registra un nuevo dato de humedad.
      tags:
      - Humedad
      x-swagger-router-controller: Humedad
    put:
      description: Modifica un dato de humedad previamente registrado
      operationId: putHumidity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Humidity'
        required: true
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Modifica un dato de humedad previamente registrado
      tags:
      - Humedad
      x-swagger-router-controller: Humedad
  /temperature:
    delete:
      description: Eliminaci贸n un dato de temperatura en la base de datos.
      operationId: deleteTemperature
      parameters:
      - description: Id del dato de temperatura
        explode: true
        in: query
        name: idTemperature
        required: true
        schema:
          format: int32
          type: integer
        style: form
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Eliminaci贸n de datos de temperatura.
      tags:
      - Temperatura
      x-swagger-router-controller: Temperatura
    get:
      description: Devuelve todos los datos relacionados con la temperatura.
      operationId: getTemperature
      parameters:
        - description: Id del invernadero
          explode: true
          in: query
          name: idGreenhouse
          required: true
          schema:
            format: int32
            type: integer
          style: form
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Devuelve todos los datos relacionados con la temperatura.
      tags:
      - Temperatura
      x-swagger-router-controller: Temperatura
    post:
      description: Creacion de nuevos datos asociados a la temperatura.
      operationId: postTemperature
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Temperature'
        required: true
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Registra un nuevo dato de temperatura.
      tags:
      - Temperatura
      x-swagger-router-controller: Temperatura
    put:
      description: Modifica un dato de temperatura previamente registrado
      operationId: putTemperature
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Temperature'
        required: true
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Modifica un dato de temperatura previamente registrado
      tags:
      - Temperatura
      x-swagger-router-controller: Temperatura
  /windows:
    get:
      description: Devuelve todos los datos relacionados con el estado Ventana
      operationId: getWindows
      parameters:
        - description: Id del invernadero
          explode: true
          in: query
          name: idGreenhouse
          required: true
          schema:
            format: int32
            type: integer
          style: form
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Devuelve todas las ventanas.
      tags:
      - Ventana
      x-swagger-router-controller: Ventana
    post:
      description: Creaci贸n de una nueva ventana
      operationId: postWindow
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Windows'
        required: true
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Registra un nuevo dato de Ventana.
      tags:
      - Ventana
      x-swagger-router-controller: Ventana
    put:
      description: Modifica un dato de ventana previamente registrado
      operationId: putWindow
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Windows'
        required: true
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Modifica un dato de ventana previamente registrado
      tags:
      - Ventana
      x-swagger-router-controller: Ventana
    delete:
      description: Eliminaci贸n un dato de ventana en la base de datos.
      operationId: deleteWindow
      parameters:
        - description: Id del dato de ventana
          explode: true
          in: query
          name: idWindow
          required: true
          schema:
            format: int32
            type: integer
          style: form
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Eliminaci贸n de datos de ventana.
      tags:
      - Ventana
      x-swagger-router-controller: Ventana
  /irrigation:
    get:
      description: Devuelve todos los datos relacionados con el riego.
      operationId: getIrrigation
      parameters:
        - description: Id del invernadero
          explode: true
          in: query
          name: idGreenhouse
          required: true
          schema:
            format: int32
            type: integer
          style: form
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Devuelve todos los datos relacionados con el riego.
      tags:
        - Riego
      x-swagger-router-controller: Riego
    post:
      description: Creacion de nuevos datos asociados al riego.
      operationId: postIrrigation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Irrigation'
        required: true
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Registra un nuevo dato de riego.
      tags:
        - Riego
      x-swagger-router-controller: Riego
    put:
      description: Modifica un dato de riego previamente registrado
      operationId: putIrrigation
      parameters:
        - description: Id del invernadero
          explode: true
          in: query
          name: idGreenhouse
          required: true
          schema:
            format: int32
            type: integer
          style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Irrigation'
        required: true
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Modifica un dato de riego previamente registrado
      tags:
        - Riego
      x-swagger-router-controller: Riego
    delete:
      description: Eliminaci贸n un dato de riego en la base de datos.
      operationId: deleteIrrigation
      parameters:
        - description: Id del dato de riego
          explode: true
          in: query
          name: idIrrigation
          required: true
          schema:
            format: int32
            type: integer
          style: form
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Eliminaci贸n de datos de riego.
      tags:
      - Riego
      x-swagger-router-controller: Riego
  /sprinklers:
    get:
      description: Devuelve todos los datos relacionados con los aspersores.
      operationId: getSprinklers
      parameters:
        - description: Id del invernadero
          explode: true
          in: query
          name: idGreenhouse
          required: true
          schema:
            format: int32
            type: integer
          style: form
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Devuelve todos los datos relacionados con los aspersores.
      tags:
        - Aspersor
      x-swagger-router-controller: Aspersor
    post:
      description: Creacion de nuevos datos asociados a los aspersores.
      operationId: postSprinklers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sprinklers'
        required: true
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Registra un nuevo dato de aspersor.
      tags:
        - Aspersor
      x-swagger-router-controller: Aspersor
    put:
      description: Modifica un dato de aspersor previamente registrado
      operationId: putSprinklers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sprinklers'
        required: true
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Modifica un dato de aspersor previamente registrado
      tags:
        - Aspersor
      x-swagger-router-controller: Aspersor
    delete:
      description: Eliminaci贸n un dato de aspersores en la base de datos.
      operationId: deleteSprinklers
      parameters:
        - description: Id del dato de aspersor
          explode: true
          in: query
          name: idSprinklers
          required: true
          schema:
            format: int32
            type: integer
          style: form
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Eliminaci贸n de datos de aspersores.
      tags:
        - Aspersor
      x-swagger-router-controller: Aspersor
  /heatings:
    get:
      description: Devuelve todos los datos relacionados con los calefactores.
      operationId: getHeatings
      parameters:
        - description: Id del invernadero
          explode: true
          in: query
          name: idGreenhouse
          required: true
          schema:
            format: int32
            type: integer
          style: form
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Devuelve todos los datos relacionados con los calefactores.
      tags:
        - Calefactor
      x-swagger-router-controller: Calefactor
    post:
      description: Creacion de nuevos datos asociados a los calefactores.
      operationId: postHeating
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Heating'
        required: true
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Registra un nuevo dato de calefactor.
      tags:
        - Calefactor
      x-swagger-router-controller: Calefactor
    put:
      description: Modifica un dato de calefactor previamente registrado
      operationId: putHeating
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Heating'
        required: true
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Modifica un dato de calefactor previamente registrado
      tags:
        - Calefactor
      x-swagger-router-controller: Calefactor
    delete:
      description: Eliminaci贸n un dato de calefactor en la base de datos.
      operationId: deleteHeating
      parameters:
        - description: Id del dato de heating
          explode: true
          in: query
          name: idHeating
          required: true
          schema:
            format: int32
            type: integer
          style: form
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Eliminaci贸n de datos de calefactor.
      tags:
        - Calefactor
      x-swagger-router-controller: Calefactor
  /greenhouse:
    delete:
      description: Eliminaci贸n de un dato de invernadero guardado en la base
        de datos.
      operationId: deleteGreenhouse
      parameters:
        - description: Id del invernadero
          explode: true
          in: query
          name: idGreenhouse
          required: true
          schema:
            format: int32
            type: integer
          style: form
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Eliminaci贸n de datos del invernadero
      tags:
        - Invernadero
      x-swagger-router-controller: Invernadero
    get:
      description: Devuelve todos los datos relacionados con el invernadero.
      operationId: getInvernadero
      parameters:
        - description: Id del usuario
          explode: true
          in: query
          name: idUsuario
          required: true
          schema:
            format: int32
            type: integer
          style: form
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Devuelve todos los datos relacionados con el invernadero.
      tags:
        - Invernadero
      x-swagger-router-controller: Invernadero
    post:
      description: Creacion de nuevos datos asociados al invernadero.
      operationId: postInvernadero
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Greenhouse'
        required: true
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Registra un nuevo dato del invernadero.
      tags:
        - Invernadero
      x-swagger-router-controller: Invernadero
    put:
      description: Modifica un dato de invernadero previamente registrado
      operationId: putInvernadero
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Greenhouse'
        required: true
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Modifica un dato de invernadero previamente registrado
      tags:
        - Invernadero
      x-swagger-router-controller: Invernadero
  /users:
    delete:
      description: Eliminaci贸n de un dato de usuario guardado en la base
        de datos.
      operationId: deleteUser
      parameters:
        - description: Id del user
          explode: true
          in: query
          name: idUsuario
          required: true
          schema:
            format: int32
            type: integer
          style: form
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Eliminaci贸n de datos del usuario.
      tags:
        - Usuarios
      x-swagger-router-controller: Usuarios
    get:
      description: Devuelve todos los datos relacionados con los usuarios.
      operationId: getUsers
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Devuelve todos los datos relacionados con los usuarios.
      tags:
        - Usuarios
      x-swagger-router-controller: Usuarios
    post:
      description: Creacion de nuevos datos asociados a los usuarios.
      operationId: postUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Registra un nuevo dato de usuario.
      tags:
        - Usuarios
      x-swagger-router-controller: Usuarios
    put:
      description: Modifica un dato de usuarios previamente registrado
      operationId: putUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        201:
          content:
            text/plain:
              schema:
                example: Created
                title: Created
                type: string
          description: Created
        404:
          content:
            text/plain:
              schema:
                example: Not found
                title: Endpoint not found
                type: string
          description: Not found response
        405:
          content:
            text/plain:
              schema:
                example: The format is not valid
                title: Invalid input
                type: string
          description: Invalid input
      summary: Modifica un dato de usuario previamente registrado
      tags:
        - Usuarios
      x-swagger-router-controller: Usuarios
components:
  responses:
    201:
      content:
        text/plain:
          schema:
            example: Created
            title: Created
            type: string
      description: Created
    404:
      content:
        text/plain:
          schema:
            example: Not found
            title: Endpoint not found
            type: string
      description: Not found response
    405:
      content:
        text/plain:
          schema:
            example: The format is not valid
            title: Invalid input
            type: string
      description: Invalid input
  schemas:
    AirQuality:
      example:
        date: "2019-01-10 13:12:35"
        amount: 45.5
        idAirQuality: 1
        idInvernadero: 1
      properties:
        idAirQuality:
          example: 1
          format: int64
          type: integer
        amount:
          example: 45.5
          type: number
        date:
          example: "2019-01-10 13:12:35"
          type: string
        idInvernadero:
          example: 1
          format: int64
          type: integer
      type: object
    Luminosity:
      example:
        idLuminosity: 1
        date: "2019-01-10 13:12:35"
        amount: 45.5
        idInvernadero: 1
      properties:
        idLuminosity:
          example: 1
          format: int64
          type: integer
        amount:
          example: 45.5
          type: number
        date:
          example: "2019-01-10 13:12:35"
          type: string
      type: object
    Notification:
      example:
        date: "2019-01-10 13:12:35"
        idNotification: 1
        isWarning: true
        problem: "Temperatura"
        status: "Low"
        idInvernadero: 1
      properties:
        idNotification:
          example: 1
          format: int64
          type: integer
        date:
          example: "2019-01-10 13:12:35"
          type: string
        isWarning:
          example: true
          type: boolean
        problem:
          example: "Temperatura"
          type: string
        status:
          example: "Low"
          type: string
      type: object
    Humidity:
      example:
        date: "2019-01-10 13:12:35"
        idHumidity: 1
        amount: 45.5
        idInvernadero: 1
      properties:
        idHumidity:
          example: 1
          format: int64
          type: integer
        amount:
          example: 45.5
          type: number
        date:
          example: "2019-01-10 13:12:35"
          type: string
      type: object
    Temperature:
      example:
        date: "2019-01-10 13:12:35"
        idTemperature: 1
        amount: 45.5
        idInvernadero: 1
      properties:
        idTemperature:
          example: 1
          format: int64
          type: integer
        amount:
          example: 45.5
          type: number
        date:
          example: "2019-01-10 13:12:35"
          type: string
      type: object
    Windows:
      example:
        idWindows: 1
        isOn: true
        affects: "Temperatura,Viento"
        name: "Lateral"
        idInvernadero: 1
      properties:
        idWindows:
          example: 1
          format: int64
          type: integer
        isOn:
          example: true
          type: boolean
        affects:
          type: string
          example: "Temperatura,Viento"
        name:
          type: string
          example: "Lateral"
        idInvernadero:
          example: 1
          format: int64
          type: integer
      type: object
    Irrigation:
      example:
        isOn: true
        idIrrigation: 1
        affects: "Temperatura,Humedad"
        idInvernadero: 1
      properties:
        idIrrigation:
          example: 1
          format: int64
          type: integer
        isOn:
          example: true
          type: boolean
        affects:
          type: string
          example: "Temperatura,Humedad"
        idInvernadero:
          example: 1
          format: int64
          type: integer
      type: object
    Sprinklers:
      example:
        isOn: true
        idSprinklers: 1
        affects: "Temperatura,Humedad"
        idInvernadero: 1
      properties:
        idSprinklers:
          example: 1
          format: int64
          type: integer
        isOn:
          example: true
          type: boolean
        affects:
          type: string
          example: "Temperatura,Humedad"
        idInvernadero:
          example: 1
          format: int64
          type: integer
      type: object
    Heating:
      example:
        value: 0
        type: "Infrarrojos"
        idHeating: 1
        affects: "Temperatura"
        idInvernadero: 1
      properties:
        idHeating:
          example: 1
          format: int64
          type: integer
        value:
          example: 0
          format: int64
          type: integer
        affects:
          type: string
          example: "Temperatura"
        type:
          type: string
          example: "Infrarrojos"
        idInvernadero:
          example: 1
          format: int64
          type: integer
      type: object
    Greenhouse:
      example:
        idUsuario: 1
        idGreenhouse: 1
        name: "Invernadero 1"
      properties:
        idGreenhouse:
          example: 1
          format: int64
          type: integer
        idUser:
          example: 1
          format: int64
          type: integer
        name:
          example: "Invernadero 1"
          type: string
      type: object
    User:
      example:
        idUsuario: 1
        idGreenhouse: 1
      properties:
        username:
          example: "user"
          type: string
        password:
          example: "pass"
          type: string
        idUser:
          example: 1
          format: int64
          type: integer
      type: object
